#!/bin/csh
set max=200
set counter=0
if (-r syslog.last) then
  tail -3 syslog.last >> runlog
endif
echo "***** Game Started at `date` [user=$user]" >> runlog
while 1
@ counter = ($counter + 1)
  echo "***** Game Booting at `date` [user=$user, run=$counter]" >> runlog
  cp -f obj/ronin bin/
  cp -f obj/roninslave bin/
  cp -f obj/list_vaults lib/vault/
  bin/ronin $1 >>& runlog
  set tmp=$status
  if (($tmp == 0) || ($counter == $max)) then
    if ((! -e syslog.last) || ((-r syslog.last) && (`tail syslog.last | grep SIGSEGV | wc -l` == 0))) then
      echo "***** Game Exited Normally at `date` [user=$user, run=$counter, status=$tmp]" >> runlog
      exit
    endif
    echo "***** Game Exited Abnormally at `date` [user=$user, run=$counter, status=$tmp]" >> runlog
  endif
  if ($tmp == 52) then
    set counter=0
  endif
  if (-r syslog.last) then
    tail -2 syslog.last >> runlog
  endif
  echo "***** Game Rebooting at `date` [user=$user, run=$counter, status=$tmp]" >> runlog
  sleep 10
end
